In [1]:
import pandas as pd
import numpy as np


In [2]:
arr=np.array([1,2,3,6,4,5])
np.flip(arr)


array([5, 4, 6, 3, 2, 1])

In [4]:
array1=np.array([[1,2,3],[2,4,5],[1,2,3]])
array1.flatten()

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

In [5]:
array1=np.array([[1,2],[3,4]])
array2=np.array([[1,2],[3,4]])
np.array_equal(array1,array2)

True

In [9]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])
def most_frequent_value_and_indices(arr):
    values,counts=np.unique(arr,return_counts=True)
    most_frequent=values[np.argmax(counts)]
    indices=np.where(arr==most_frequent)[0]
    print("Most Frequent",most_frequent)
    print("Indices",indices)
most_frequent_value_and_indices(x)
most_frequent_value_and_indices(y)


Most Frequent 1
Indices [0 5 7 8 9]
Most Frequent 1
Indices [0 1 2]


In [10]:
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')
print(np.sum(gfg))
print(np.sum(gfg,axis=1))
print(np.sum(gfg,axis=0))

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [11]:
n_array=np.array([[55,25,15],
                 [30,44,2],
                 [11,45,77]])
print("trace",np.trace(n_array))
values,vectors =np.linalg.eig(n_array)
print("eigenvalues",values)
print("eigenvectors",vectors)
print("inverse",np.linalg.inv(n_array))
print("determinant",np.linalg.det(n_array))

trace 176
eigenvalues [98.16835147 28.097044   49.73460452]
eigenvectors [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
inverse [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
determinant 137180.0000000001


In [12]:
p1=[[1,2],[2,3]]
q1=[[4,5],[6,7]]
print("dot",np.dot(p1,q1))
print("cov",np.cov(p1,rowvar=False))


dot [[16 19]
 [26 31]]
cov [[0.5 0.5]
 [0.5 0.5]]


In [13]:
x=np.array([[2,3,4],[3,2,9]])
y=np.array([[1,5,0],[5,10,3]])
print("inner",np.inner(x,y))
print("outer")
print(np.outer(x.flatten(),y.flatten()))

inner [[17 52]
 [13 62]]
outer
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


In [15]:
array=np.array([10,52,62,16,16,54,453])
print("sort",np.sort(array))
print("argsort",np.argsort(array))
print("4 smallest elements",np.sort(array)[:4])
print("5 largest elements",np.sort(array)[-5:])

sort [ 10  16  16  52  54  62 453]
argsort [0 3 4 1 5 2 6]
4 smallest elements [10 16 16 52]
5 largest elements [ 16  52  54  62 453]


In [16]:
array=np.array([1.0,1.2,2.2,2.0,3.0,2.0])
integer_elements=array[np.equal(np.mod(array,1),0)]
float_elements=array[np.not_equal(np.mod(array,1),0)]
print("integer_elements_only",integer_elements)
print("float_elements_only",float_elements)

integer_elements_only [1. 2. 3. 2.]
float_elements_only [1.2 2.2]


In [17]:
array=np.array([[1,-2,3],[-4,5,-6]])
print("absolute",np.abs(array))
print(np.percentile(array, [25,50,75]))
print(np.percentile(array, [25,50,75],axis=0))
print(np.percentile(array, [25,50,75],axis=1))
print(np.mean(array))
print(np.median(array))
print(np.std(array))

absolute [[1 2 3]
 [4 5 6]]
[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
-0.5
-0.5
3.8622100754188224


In [18]:
a=np.array([-1.8,-1.6,-0.5,0.5,1.6,1.8,3.0])
print("floor",np.floor(a))
print("trunc",np.trunc(a))
print("ceil",np.ceil(a))
print("round",np.round(a))

floor [-2. -2. -1.  0.  1.  1.  3.]
trunc [-1. -1. -0.  0.  1.  1.  3.]
ceil [-1. -1. -0.  1.  2.  2.  3.]
round [-2. -2. -0.  0.  2.  2.  3.]
